language: c
sudo: required
dist: trusty
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
    global:
        - TESTS=false
    matrix:
        - OCAML_VERSION=4.06 EXTRA_DEPS="solo5-kernel-ukvm"
        - OCAML_VERSION=4.06 EXTRA_DEPS="solo5-kernel-virtio"
        - OCAML_VERSION=4.06 EXTRA_DEPS="solo5-kernel-muen"
        - OCAML_VERSION=4.05 EXTRA_DEPS="solo5-kernel-ukvm"
        - OCAML_VERSION=4.05 EXTRA_DEPS="solo5-kernel-virtio"
        - OCAML_VERSION=4.05 EXTRA_DEPS="solo5-kernel-muen"
        - OCAML_VERSION=4.04 EXTRA_DEPS="solo5-kernel-ukvm"
        - OCAML_VERSION=4.04 EXTRA_DEPS="solo5-kernel-virtio"
        - OCAML_VERSION=4.04 EXTRA_DEPS="solo5-kernel-muen"
